### ISSUE TITLE
Bug: 404 margherita-pizza.png

### ISSUE THREAD

**Issue by bdougie** [open-sauced/pizza-verse#11]
### Describe the bug

https://github.com/open-sauced/pizza-verse/blob/main/images/margherita-pizza.png is a 404

### Steps to reproduce

Needs to swap `-` for `_`

https://github.com/open-sauced/pizza-verse/blob/main/images/margherita_pizza.png

### Browsers

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by BlackBond06** [comment]
Hi @bdougie, thanks for the assign.

Please, can I get more context about the issue?
