### ISSUE TITLE
Feature: Add a section for Regional Pizza

### ISSUE THREAD

**Issue by BekahHW** [open-sauced/pizza-verse#17]
### Type of feature

🍕 Feature

### Current behavior

We currently have categories for pizza recipes and facts. It would be nice for people to be able to add their regional pizza styles to this repo as well.

### Suggested solution

- Add a section for regional pizza styles in the readme that replicates facts and recipes
- Create a `regional-pizza.md` file and replicate the organization of `pizza-facts.md`
- remove the [pizza styles section](https://github.com/open-sauced/pizza-verse/blob/main/pizza-facts.md#pizza-styles) from the facts doc.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
That's a great idea @BekahHW! :) This would be a great way for contributors to introduce themselves. I'll make the PR for this if you're open.

**Comment by CBID2** [comment]
Made the PR @BekahHW! :)
