### ISSUE TITLE
README references non existent pizza, Facts and Recipes folders 

### ISSUE THREAD

**Issue by jdwilkin4** [open-sauced/pizza-verse#2]
In the [README](https://github.com/jdwilkin4/pizza-verse#readme) under the ["How to Contribute"](https://github.com/jdwilkin4/pizza-verse#how-to-contribute) section, there are references to folders that are non existent in the repo. 

The issue lies within steps 3-5 here:

3. Inside the repository, navigate to the `pizza` folder.
4. Choose an appropriate subfolder (e.g., `Facts`, `Recipes`) to add your content.
5. Create a **new markdown file** in the chosen subfolder.

The repo currently does not have a `pizza` folder or `Facts` and `Recipes` subfolders.

## Suggested fix
Add in the missing folders to the repo so contributors can add in their new recipes and pizza facts. 👍 

OR

If the goal is to have contributors directly edit the `pizza-facts` and `pizza-recipes` files, then I would suggest the following changes to the README.

1. **Fork** this repository to your own GitHub account.
2. **Clone** the forked repository to your local machine.
3. Add a new pizza fact to the `pizza-facts.md` file or choose to add a new recipe to the `pizza-recipes.md` file. 
4. Follow the existing markdown syntax to format your content. Feel free to add headings, bullet points, images, and links to enhance your contribution.
5. Once you're done, **commit** your changes and **push** them to your forked repository.
6. Submit a **pull request** to have your contribution reviewed and considered for merging into the main repository.
7. Engage with other contributors and maintainers through comments and discussions.

Hope that helps 😄

**Comment by Sanjay-shankar** [comment]
@jdwilkin4 Even I was looking for the 'Pizza' folder. When will the issue be fixed?

**Comment by jdwilkin4** [comment]
@Sanjay-shankar 

I would wait to hear back from the maintainers of the project and they will let us know when the issue will be resolved.

**Comment by Sanjay-shankar** [comment]
@jdwilkin4 Alright, Thanks.

**Comment by BekahHW** [comment]
So sorry! I restructured the project and forgot to update the readme. 

I can't make the changes now, but you just need to navigate to the markdown file and add your entry to the correct file. 

So you should not be creating a new markdown file.

**Comment by Sanjay-shankar** [comment]
@BekahHW Alright, Thanks for clarifying.

**Comment by jdwilkin4** [comment]
Hey @BekahHW ! 

Thank you for your quick response 😃 

If you would like, I would be happy to create a PR to update the README with the updated instructions

**Comment by BekahHW** [comment]
@jdwilkin4 I would really appreciate that.
