### ISSUE TITLE
Feature: Pizza education and learning resources

### ISSUE THREAD

**Issue by Lymah123** [open-sauced/pizza-verse#23]
### Type of feature

🍕 Feature

### Current behavior

- There is no resources to learn pizza.

### Suggested solution

- Pizza-Making Courses and Workshops
- Recommended Books and Documentaries
- Online Pizza Communities and Forums

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Hi @Lymah123.  The [pizza history](https://github.com/open-sauced/pizza-verse/blob/main/Pizza-history.md),[pizza triva](https://github.com/open-sauced/pizza-verse/blob/main/pizza-facts-%26-trivia.md),[regional pizza](https://github.com/open-sauced/pizza-verse/blob/main/regional-pizza.md), and [recipes](https://github.com/open-sauced/pizza-verse/blob/main/pizza-recipes.md) seem to provide the resources you're listing. How about you recommend specific resources to add to one of the files instead?

**Comment by Lymah123** [comment]
@CBID2 , do you mean like adding to the files based on the sections we already have? I was thinking of adding a subsection. Let me know what you suggest.

**Comment by CBID2** [comment]
> @CBID2 , do you mean like adding to the files based on the sections we already have? I was thinking of adding a subsection. Let me know what you suggest.

Yeah that's what I was thinking @Lymah123. Like adding a pizza recipe you've made to the `recipes.md` file. We're trying to keep this repo simple so beginners won't be too overwhelmed.

**Comment by Lymah123** [comment]
Alright @CBID2 , I will do that

**Comment by Lymah123** [comment]
@CBID2 , can you assign this to me? I have started working on it.
