### ISSUE TITLE
Feature: I want to add more pizza facts in Pizza Facts & Trivia

### ISSUE THREAD

**Issue by kumar007ambi** [open-sauced/pizza-verse#28]
### Type of feature

🍕 Feature

### Current behavior

I want to add more pizza facts in Pizza Facts & Trivia section for the information.

### Additional context

I was wondering can admin add hactoberfest label or not ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by kumar007ambi** [comment]
@CBID2 I was wondering can admin add hactoberfest label or not ?

**Comment by CBID2** [comment]
> @CBID2 I was wondering can admin add hactoberfest label or not ?

Done

**Comment by kumar007ambi** [comment]
Already added to the page
