### ISSUE TITLE
Feature: Change in rules 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/pizza-verse#31]
### Type of feature

🍕 Feature

### Current behavior

There have been concerns about merge conflicts occurring due to PRs with large numbers of content being added to the recipe and pizza-facts-and-trivia files

### Suggested solution

1. Add in new rules to [the contributing guidelines section](https://github.com/open-sauced/pizza-verse#contribution-guidelines), such as "To keep things organized, You choose to either add one new pizza fact to the `pizza-facts.md` file or add one new recipe to the `pizza-recipes.md` file."
2. Create a section that looks similar to [the Resolving Conflicts section in the Contributing guide in the `guestbook` repository](https://github.com/open-sauced/guestbook#resolving-merge-conflicts). 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by Lymah123** [comment]
@CBID2 : )!

**Comment by jdwilkin4** [comment]
Hey @CBID2 ! 

I would also suggest adding a link to an article or video on how to resolve merge conflicts so if a beginner does run into that issue, even with the change in rules, they will know how to resolve it.
Maybe a short opensauced link would work in this case.

Just food for thought 👍

**Comment by CBID2** [comment]
> Hey @CBID2 ! 
> 
> 
> 
> I would also suggest adding a link to an article or video on how to resolve merge conflicts so if a beginner does run into that issue, even with the change in rules, they will know how to resolve it.
> 
> Maybe a short opensauced link would work in this case.
> 
> 
> 
> Just food for thought 👍 
> 
> 

Good idea @jdwilkin4! 😃 @adiati98 is working on a PR for merge conflicts. I'll add a link to that once it's merged. 😃

**Comment by adiati98** [comment]
Hey @BekahHW @CBID2,

Should I submit separate PR for:
1.  Changing the rule
2. Adding a resolving conflict section. 

Or should I put them in the same PR?

**Comment by CBID2** [comment]
> Hey @BekahHW @CBID2,
> 
> 
> 
> Should I submit separate PR for:
> 
> 1.  Changing the rule
> 
> 2. Adding a resolving conflict section. 
> 
> 
> 
> Or should I put them in the same PR?

@adiati98, creating separate PRs does sound best :)
