### ISSUE TITLE
Feature: I want to add a Pizza recipe

### ISSUE THREAD

**Issue by kumar007ambi** [open-sauced/pizza-verse#37]
### Type of feature

🍕 Feature

### Current behavior

I want to add a Indian Pizza Recipe which is quite popular in India.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Hi @kumar007ambi. You can mention this in the comment section of issue #35, so I'm going to close this one.

**Comment by kumar007ambi** [comment]
okay
