### ISSUE TITLE
Bug: I have a question regarding table of contents of recipes ?

### ISSUE THREAD

**Issue by kumar007ambi** [open-sauced/pizza-verse#41]
### Describe the bug

In the table of contents present 4 contents are available. Should the number of contents added for more added pizza recipes ?

### Steps to reproduce

Add newly added recipes to the table contents.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by adiati98** [comment]
Hey @kumar007ambi 
Thank you for submitting this issue.

But I'm not quite sure what you mean by adding more table of contents. Can you explain more?

**Comment by kumar007ambi** [comment]
@adiati98 At first only 4 recipes were there but right now 6 recipes are available. So the number of table of contents should be increased for example Chicken tikka masala pizza and Nigeria pizza shoibe added in the table context.

**Comment by CBID2** [comment]
> @adiati98 At first only 4 recipes were there but right now 6 recipes are available. So the number of table of contents should be increased for example Chicken tikka masala pizza and Nigeria pizza shoibe added in the table context.

So you're asking if you should add these two new recipes to the TOC @kumar007ambi?

**Comment by kumar007ambi** [comment]
@CBID2 Absolutely Correct

**Comment by CBID2** [comment]
> @CBID2 Absolutely Correct

Great thanks for clarifying @kumar007ambi! 😄 You've been assigned to the issue! :) Please keep the following in mind as you make your PR(this is mostly a refresher):

1. Create a separate branch with Git before you push your commits. If you need help with this, check out [this article, How to Create a Local Branch in Git](https://www.freecodecamp.org/news/how-to-create-a-local-git-branch/)
2. Follow the directions in the PR template to fill it out completely. If you need more tips, check out the blog post, [Writing Your First Pull Request: Tips, Best Practices, and AI-Powered Tools for Success](https://dev.to/opensauced/writing-your-first-pull-request-tips-best-practices-and-ai-powered-tools-for-success-3bg9)

**Comment by kumar007ambi** [comment]
@CBID2 I have a question regarding creating new branch. Because I have a separte branch from main where I have contributed recipes and info. So I have to create a separate branch for regarding this issue ?

**Comment by kumar007ambi** [comment]
@CBID2 Okay I will create a new branch for this issue.

**Comment by adiati98** [comment]
Closed with PR #42.
