### ISSUE TITLE
Feature:  Markdown Style reference 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/pizza-verse#7]
### Type of feature

📝 Documentation

### Current behavior

Even though the ReadMe file suggests following the markdown syntax based on the other entries, contributors, especially those who never used this language before would have a hard time remembering how to format their contribution. 

### Suggested solution

I think it would be helpful to create some sort of Markdown reference guide. It'll make it easier for contributors, especially those who have never used Markdown before to gain a better understanding of how to format their contribution. 
Note: I would love to create this guide.   

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
This is what I learned from years ago. We can either link to it or create a quick reference guide.

https://daringfireball.net/projects/markdown/basics

**Comment by CBID2** [comment]
Hey @bdougie! :) I created the PR! :) It's #8. I don't know when @BekahHW will return, but can you review it just in case?
