### ISSUE TITLE
docs: Grammar and Formatting issues 

### ISSUE THREAD

**Issue by CBID2** [open-sauced/pizza-verse#70]
### Type of feature

🍕 Feature

### Current behavior

The [style guide](https://github.com/open-sauced/pizza-verse/blob/main/style-guide.md) has a few Markdown errors and grammar issues. This can make it difficult for people to implement the guidelines effectively when making their contribution to this project. 

### Suggested solution

- [ ] Remove the gap in `> ** Note:** Always check for spelling and grammar errors before you publish your PR. We highly recommend consulting [Grammarly](https://www.grammarly.com/) to help with any of your typos.`. This would clarify to people that checking for spelling is needed when making their contribution.
- [ ] Omit the word "to" in the sentence, `Said images should be linked to using the following url: "https://raw.githubusercontent.com/open-sauced/pizza-verse/main/images/" followed by the image’s name.` for clarity. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [x] I agree to follow this project's Contribution Docs

**Comment by codewithjazzy** [comment]
.take

**Comment by codewithjazzy** [comment]
take
